name: stringly
description: "stringly"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+19

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_icp_auth: ^2.0.1
  agent_dart: ^1.0.0-dev.22
  archive: ^3.1.2
  firebase_core: ^3.9.0
  firebase_analytics: ^11.3.6
  firebase_storage: ^12.3.7
  google_maps_flutter: ^2.10.0
  geocoding: ^3.0.0
  google_places_flutter: ^2.0.9
  geolocator: ^10.1.1
  permission_handler: ^10.0.0
  socket_io_client: ^3.0.2
  image: ^4.3.0
  path_provider: ^2.1.5
  google_place: ^0.4.7
  cupertino_icons: ^1.0.8
  dropdown_textfield: ^1.2.0
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  photo_manager: ^3.6.1
  camera: ^0.11.0+2
  video_player: ^2.9.2
  animated_splash_screen: ^1.3.0
  google_fonts: ^6.2.1
  get: ^4.6.6
  csc_picker: ^0.2.7
  get_storage: ^2.1.1
  http: ^1.2.2
  intl: ^0.18.0
  flutter_svg: ^2.0.16
  uuid: ^4.4.2
  flutter_sound: ^9.19.1
  audioplayers: ^6.1.0
  flutter_local_notifications: ^18.0.1
  workmanager: ^0.5.2
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  image_cropper: ^5.0.1
  flutter_dotenv: ^5.2.1
  just_audio: ^0.9.46
  url_launcher: ^6.3.1

dependency_overrides:
  http: ^0.13.1
  uni_links: ^0.5.0
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/hobbies/
    - assets/socialMedia/
    - assets/svg/
    - assets/newNavBarIcon/
    - assets/newImage/
    - .env
